language: go
sudo: false 
go:
  - "1.11"
install:
  - "go mod download"
env:
  global:
    - NAME=clash
    - BINDIR=bin
    - GO111MODULE=on
script:
  - go test ./...
before_deploy: make -j releases
deploy:
  provider: releases
  prerelease: true
  skip_cleanup: true
  api_key: 
   secure: "fYbfqHv2WtmWCy4ANq7q5RBGY1xNQZsB+L+IhkuoXvex9SmT+AcEiZziOR8qss5CrOuqqD6xf5Vx7UuqAopuE7swgU01h6aqQDA505U6xmb/EmEHb+AqRKBe9I9pMVK5r7qM3W1vOWfKmf4iqLno8GOYYMlyhTqNdiYxrbCW64aA4qB86UuyiGpemiUqVGx7SlCEqHHqErLj4hQAlrMWubfVEr5Ncx3NxQA6ISQCPlRIrcFyQSTsdgEnP7zoUTT+qcT9FQctumsxiWaZ/MseZAo3QS1LtiNvO9ZWUypLPBzSZBF1mMBG7lUpy2IyH4uK3rObozqqiEIOkxqxBfYuViC5aSXQ6c6PlKaVp3jb/6Z94Kb4SjgXxLuXiENuqEaTwIZSfIKjPUAeC0xBySIOn2hVWp8++AGSqlDhAeit1hYCrDOjHRl3LrUl5kKWUy79i6itl0WVU1bl2o4rfO8SOJjmm0r83aMDKLfcmzNLexh3OBx6CgA9XbSVcaHYloGK4xUvt4j02fyLC2UU57IXwe8BHej3Naps4YiWHiNdKNHkMPHQLhm98wq2wCHsbzX/VyKekRX2ZXzpxsujajA/kDCTc058LLmihPZ3ycgWBKJhsiFPQP4RUI7zqzDv80YnWfI9DlL3qFIjekAcpzyCoGkZDmmaUEys0mTaJxIr3mE="
  file: bin/*
  file_glob: true
  on:
    repo: alliswell2day/clashxx
    branch: master
    tags: true
