language: go
sudo: false
go:
  - "1.11"
install:
  - "go mod download"
env:
  global:
    - NAME=clash
    - BINDIR=bin
    - GO111MODULE=on
script:
  - go test ./...
before_deploy: make -j releases
deploy:
  provider: releases
  prerelease: true
  skip_cleanup: true
  api_key: ""
  file: bin/*
  file_glob: true
  on: 
    repo: alliswell2day/clash
    branch: dev
    tags: no
