language: go
sudo: false 
go:
  - "1.11"
install:
  - "go mod download"
env:
  global:
    - NAME=clash
    - BINDIR=bin
    - GO111MODULE=on
script:
  - go test ./...
before_deploy: make -j releases
deploy:
  provider: releases
  prerelease: true
  skip_cleanup: true
  api_key:
   secure: "oYxZz8oYybi4TMyolN/4BIqLHLcn026o6T+r+HBiRdfl95JgPFHFst3BRW5aFoVpnehRhgjF7hgXx48D+cpbbcG+8mEtq60fM/ONk5zxK7tI0gTDYxPq/i1c2df37Xrdn5Sf/3wvZ86G5X6kRXInYILKfRf4cGcmnqR54N15sHCAqG8+3qwX3lzz22Gqx0/og8yn0CGz2HsfhfugNpZvzzYaSdGwkeUranWA/cwKJK6AbE1qpx/mHawcwF6T1Eph2lkQMQw3aFTdXYnxaX4hDGBbRC/DKKV3aWUcfFgLjNxTeJy01qcx7YFjGR2W+QXrhrCYz+PJz4NszVPJNGj+oQDeMlYXNzJqTvb5gk7JnQERCun92fcWGi4UIwwmlBNI0K/K9KHW4cYUwJ7SSbtfJNGZx7eWEuQBgNEFo9QMbuu/nrn2LjdaqCKZDapwSUikMs8t2kWaJGOQVH9seUR+/SIrQnq/7Scftr1RnpQZMrpDk8J15unKMNAUf4vDZDiCNwBQfuWqP0tcCV+rr7oE9LgBhS4K8oaFuNGGk3dNjQr0v8cQzab2Tg702Gm3Uf/VMt19z7EB3kSxzDeJUklPO22Mun71qYMSrqkI2SaT+nwRdrqqQUnhB3fBxCEDMz0EnvCuXN5Hq9EUvwu7S/z+Vd02vXZbmtMpT2cXTVDNtYE="
   file: bin/*
  file_glob: true
  on:
    repo: alliswell2day/clashxx 
    branch: master 
    tags: no
