language: go
sudo: false 
go:
  - "1.11"
install:
  - "go mod download"
env:
  global:
    - NAME=clash
    - BINDIR=bin
    - GO111MODULE=on
script:
  - go test ./...
before_deploy: make -j releases
deploy:
  provider: releases
  prerelease: true
  skip_cleanup: true
  api_key:
   secure: "vvc2oiljmvP7GTQRXofd8A2DXnqeQYiOI90fbskt1WnYYtnVWWNTKkHznaqiN/Z6hInHyPSRQ1hkYxcu9+8HAYne2BxW91ccN4yOJahJqL5ShoiDPt1hU5kKGfToB7quqJyEwfj14iZSIfryZvSB75dyWduiR0hqz8AgWsCosPOBZUevwIJjPj/N2F+XPv8f7lSPDMAqHXd9BFvy3B9vLXztN6TGfzl61w8+1humcmhu59fqlY5hCfF0ZPK/DaqVYB3slMt4zVXsVZjjIOzyW2HK8gh6cZtj7HmXVWBqViWP/gb8VB2eiwTtWl8PK7VsdA8vuIu5OC0OwzAOgVXgt+mmHBupVT1fof63nb2HrrVnno8raE5RwnTQK/Lx9pu5mPuAPJY/1B6ZriIOxG8958DG0SC07eRsciVUv5yg0SDI7RL7OdpFgxCmZdLJkK6502caVyx15uvY0LYGuDtrMymRWKWCHF57qndlPo9+GpiUv0l/x5j3r0RAGBYamZhYcEqmCE2K6FBj7EavjcT4pP/4A8rmVLVi59UR5yZmRu1K7D6ub4M3nIyTDNlYzmTia4BIWkPz8j9Bwqmk0Ccjha7bXco6Gt6yLW7+VUSFxLpTER6fzukMvNnmsMTI5x0thMjay7FMeVDSViiDshA0bAhuWVR54VqfYTA+UY6hVFQ="
   file: bin/*
  file_glob: true
  on:
    repo: alliswell2day/clashxx 
    branch: master
    tags: true
